{% set name = "loopstructural" %}

package:
  name: "{{ name|lower }}"
  version: "{{ environ.get('GIT_DESCRIBE_TAG', '') }}"

source:
  git_url: https://github.com/Loop3D/LoopStructural

build:
  number: 0
  script: "{{ PYTHON }} -m pip install ."

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - numpy >=1.18
    - pandas
    - scipy
    - scikit-image
    - scikit-learn
    - tqdm

test:
  imports:
    - LoopStructural
  commands:
    - pip check
  requires:
    - pip


about:
  home: "https://github.com/Loop3D/LoopStructural"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Implicit 3D geological modelling library"
  doc_url: "https://loop3d.github.io/LoopStructural/"
  dev_url: 

extra:
  recipe-maintainers:
    - lachlangrose
