on:
  push:
    branches:
      - master
env:
    PACKAGE_NAME: LoopStructural

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v4
        id: release
        with:
          release-type: python
          package-name: LoopStructural
          version-file: LoopStructural/version.py
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
  package:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - name: Trigger build for pypi and upload
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Loop3d/${{env.PACKAGE_NAME}}/actions/workflows/pypi.yml/dispatches \
          -d '{"ref":"master"}'
      - name: Trigger build for conda and upload
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Loop3d/${{env.PACKAGE_NAME}}/actions/workflows/conda.yml/dispatches \
          -d '{"ref":"master"}'

  
