name: "🎳 Tester"

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - .github/workflows/tester.yml

  pull_request:
    branches:
      - main
    paths:
      - '**.py'
      - .github/workflows/tester.yml
jobs:
  continuous-integration:
    name: Continuous integration ${{ matrix.os }} python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(vars.BUILD_OS)}}
        python-version: ${{ fromJSON(vars.PYTHON_VERSIONS)}}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3

        with:
          python-version: ${{ matrix.python }}
      - name: Installing dependencies
        shell: bash -l {0}
        run: |
          conda install -c conda-forge numpy scipy scikit-image scikit-learn pytest networkx osqp matplotlib -y
      - name: Building and install
        shell: bash -l {0}
        run: |
          pip install . --user
      - name: pytest
        shell: bash -l {0}
        run: |
          pytest
